# Generated by Django 2.0 on 2018-04-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='titulo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('due_date', models.DateField(verbose_name='data de vencimento')),
            ],
        ),
    ]
