# Generated by Django 2.0 on 2018-04-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('date', models.DateField(verbose_name='data de vencimento')),
                ('symbol', models.CharField(max_length=255, verbose_name='simbolo')),
                ('shares', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cotas')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='taxas')),
                ('type', models.CharField(max_length=255, verbose_name='operação')),
                ('note', models.CharField(max_length=255, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'ativo',
                'verbose_name_plural': 'ativos',
            },
        ),
    ]
