# Generated by Django 2.0 on 2018-05-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(verbose_name='data de compra'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('B', 'Compra'), ('S', 'Venda')], default='B', max_length=2, verbose_name='operação'),
        ),
    ]
