# Generated by Django 2.0 on 2018-05-21 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180520_2003'),
        ('core', '0005_auto_20180520_2019'),
    ]

    operations = [
    ]
