# Generated by Django 2.0 on 2018-05-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20180520_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='operation',
            field=models.CharField(choices=[('B', 'Compra'), ('S', 'Venda')], default='B', max_length=2, verbose_name='operação'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('share', 'ação')], default='share', max_length=2, verbose_name='tipo'),
        ),
    ]
