# Generated by Django 2.0 on 2018-05-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180520_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('share', 'ação')], default='share', max_length=50, verbose_name='tipo'),
        ),
    ]
